# Generated by Django 4.1.5 on 2023-01-18 08:48

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('landmark', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to=home.models.get_filepath)),
            ],
            options={
                'db_table': 'SellProperty',
            },
        ),
    ]
