# Generated by Django 4.1.5 on 2023-01-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='category',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Short Time', 'Short Time')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='location',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('TamilNadu', 'TamilNadu'), ('Karnataka', 'Karnataka')], max_length=200, null=True),
        ),
    ]
