# Generated by Django 4.1.5 on 2023-01-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registeruser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registeruser',
            table='RegisterUser',
        ),
    ]
