# Generated by Django 4.1.5 on 2023-01-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sellproperty_user_remove_customer_user_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproperty',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
    ]
