# Generated by Django 4.1.5 on 2023-01-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sellproperty_customer_alter_sellproperty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='type',
            field=models.CharField(choices=[('Land', 'Land'), ('House', 'House'), ('Villas', 'Villas'), ('PG', 'PG')], max_length=200, null=True),
        ),
    ]
