# Generated by Django 4.1.5 on 2023-01-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
