# Generated by Django 4.1.5 on 2023-01-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_buyer_date_created_buyer_name_customer_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emirequest',
            name='buyer',
        ),
        migrations.AddField(
            model_name='emirequest',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sellproperty'),
        ),
    ]
