# Generated by Django 4.1.5 on 2023-01-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_emirequest_buyer_emirequest_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='emirequest',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
