# Generated by Django 4.1.5 on 2023-01-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_emirequest_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
        migrations.AddField(
            model_name='emirequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
    ]
