# Generated by Django 4.1.5 on 2023-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_buyer_customer_emirequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='emirequest',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
