# Generated by Django 4.1.5 on 2023-01-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_emirequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='baths',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='bed',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
